apiVersion: v1
kind: Service
metadata:
  name: adguard-home-service
  namespace: adguard-home
spec:
  selector:
    app: adguard-home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: admin
  type: ClusterIP